# Aula 1 - Explicações sobre a sintaxe da linguagem Python

### Dois pontos sinaliza o início de uma sentença composta
#### O conteúdo das sentenças compostas é aninhado com espaços/tabs, sem chaves

In [1]:
# 1) Criar uma sentença composta (if else)
# 2) Mostrar aninhamento com tabulação
# 3) ; é opcional
# 4) imprimir valores dentro do if else como feedback
x = 2
if x > 0:
      # adiciona 1 a x
      x = x + 1;  # Ponto e virgula para finalizar uma sentença é opcional
      print(x)
      print('x maior que zero')
else:
      print('x menor ou igual a zero')


3
x maior que zero


### Referências para objetos não possuem um tipo associado
#### Não há problema em reatribuir uma referência a outro tipo

In [8]:
# 1) Atribuir um número a uma variável, 
# e em sequencia atribuir um conteúdo de tipo diferente à mesma variável
# 2) imprimir os tipos da variável como feedback
x=2
print(type(x))
x='carro'
print(type(x))

<type 'int'>
<type 'str'>


### Funções são declaradas com a palavra-chave def
### Argumentos são passados por referência, e não por valor na chamada de funções

In [8]:
# 1) criar uma função qualquer (por exemplo, insert_1)
# 2) aplicar a função a uma variável
# 3) mostrar que os argumentos são passados por referência para objetos
def insert_1(a): # A função não retorna nenhum objeto
    a.append(1) # O objeto apontado pela referência a foi alterado

b = [2]
insert_1(b)
print(b)


[2, 1]


### Formando uma string

In [1]:
# 1) Criar uma string a partir de parâmetros

a = 4.5
b = 2
frase = f'a={0}, b={1}'
print(frase)

a=0, b=1


### Imports
#### Um módulo é um arquivo de extensão .py. Útil para reusabilidade de código.

In [2]:
import os
import sys
module_path = os.path.abspath('.')
sys.path.append(module_path)

In [3]:
# O arquivo modulo_exemplo.py está no diretório Aula1/modulos
# 1) Importar a função insert1 do modulo_exemplo.py
# 2) Aplicar a fórmula insert1 e imprimir o resultado

from modulos.modulo_exemplo import insert1
b = [2]
insert1(b)
print(b)

[2, 1]


In [12]:
# O módulo "os" fornece vários métodos para manipulação de arquivos e diretórios.
# O método getcwd (get current work directory) retorna o diretório corrente
# 1) Importar o módulo os
# 2) Imprimir o diretorio de trabalho (diretorio corrente)

import os
print(os.getcwd())

C:\Users\alex\Google Drive\Aulas\Enap\BootcampTI2020\Modulo2\AnaliseDeDados_Teste1\Aulas\notebook\Aula1


### Conversão de Tipos
#### str, bool, int, e float também são funções para converter valores para esses tipos

In [13]:
# 1) Criar uma variavel do tipo string
# 2) Converte-la para float
# 3) Converter o float resultante para int
s = '3.14159'
fval = float(s)
ival = int(fval)
print(fval)
print(ival)

3.14159
3


### Laços (loops) do tipo for
#### Uma maneira de iterar sobre uma coleção. Usa-se o keyword *in* para referenciar a coleção.

In [14]:
# 1) Criar uma sequencia de números inteiros contendo o numero 5 em alguma posição
# 2) Fazer um laço para ler os valores de forma sequencial e somá-los até encontrar 
#     o número 5. Não incluir o número 5 na soma.
# 3) Imprimir o valor da soma

# val foi um termo escolhido pelo programador

sequence = [1, 2, 0, 4, 6, 5, 2, 1]
total_until_5 = 0
for val in sequence:
    if val == 5:
        break  # Interrompe um laço/loop/iteração
    total_until_5 += val
print(total_until_5)

13


# Estrutura de Dados em Python

### Lista é uma sequência de tamanho variável e conteúdo mutável (alterável)
#### Assim como as tuplas, a lista pode conter objetos de vários tipos. Define-se uma lista com colchetes [ ]
#### Use append para inserir elementos, pop para remover elementos pelo índice

In [5]:
# 1) Criar uma lista com elementos de diferentes tipos. Exemplo: [2, 4, 0, None]
# 2) Adicionar um elemento com o método append
# 3) Remover e recuperar o elemento de índice 1
# 4) Remover o elemento de valor 0

al = [2, 4, 0, None]
print(al)
al.append(9)
print(al)
al.pop(1) # Remover pelo índice
print(al)
# Use remove para remover pelo valor
al.remove(0)
print(al)

[2, 4, 0, None]
[2, 4, 0, None, 9]
[2, 0, None, 9]
[2, None, 9]


### Combinando Listas
#### Use o operador + ou a função extend. A função extend é mais rápida do que o operador +

In [7]:
# 1) Criar uma lista com elementos de diferentes tipos, chamada a1. Ex.: [2, 4, 0, None]
# 2) Criar uma nova lista, al_plus, com os elementos de duas listas usando o operador +
# 3) Adicionar os elementos de uma outra lista à lista a1
# 4) Comparar o conteúdo das duas listas a1 e a1_plus

al = [2, 4, 0, None]
al_plus = al + ['a', 'b']
al.extend(['a', 'b'])
comp = al_plus == al
print(comp)

True


### Teste de desempenho  ( curiosidade )

In [8]:
import timeit
print("extend")
extend_str = '''everything = []
list_of_lists = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] for i in range(0,1000)]
for chunk in list_of_lists:
    everything.extend(chunk)'''

t1 = timeit.timeit(extend_str, number=100)  # number representa a qtd de vezes que vai executar o comando

extend


In [9]:
print("plus")
plus_str = '''import random
everything = []
list_of_lists = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] for i in range(0,1000)]
for chunk in list_of_lists:
    everything = everything + chunk'''

t2 = timeit.timeit(plus_str, number=100)  # number representa a qtd de vezes que vai executar o comando

plus


In [10]:
print(t1)
print(t2)
print(t2/t1)

0.0691249
1.7083982
24.7146570917


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### Slicing (fatiar)
#### Use intervalos entre colchetes para fatiar sequências

In [1]:
# 1) Criar uma lista com vários elementos
# 2) Imprimir os elementos de índice 0 a 3 (são os 4 primeiros elementos)
# 3) Imprimir os elementos de índice 0 a 4, suprimindo o parametro esquerdo do intervalo
# 4) Imprimir os elementos de índice 2 até o último
# 5) Imprimir o último elemento
# 6) Imprimir a cada dois elementos
# 7) Imprimir os elementos espelhados/revertidos
# 8) Atribuir uma lista a um slice (uma parte) da lista original

al = [2, 4, 0, 3, 7, 10, 4, 5]
print(al[0:3])  # De zero a 3
print(al[:4])   # De zero a 4
print(al[2:])   # De 2 até o último
print(al[-1])   # O último element
print(al[::2])  # A cada dois elementos
print(al[::-1]) # Reverter/espelhar os elementos
al[1:3] = [8, 8]
print(al)

[2, 4, 0]
[2, 4, 0, 3]
[0, 3, 7, 10, 4, 5]
5
[2, 0, 7, 4]
[5, 4, 10, 7, 3, 0, 4, 2]
[2, 8, 8, 0, 3, 7, 10, 4, 5]


### Dicionário (dict)
### Uma coleção de key-value (chave-valor) de tamanho flexível
#### O key e o value podem ser qualquer objeto python

In [4]:
# 1) Criar um dicionário com as seguintes informações de um veículo: 
#      tipo=carro, ano=2020, ocupacao= 1 e 2
# 2) Adicionar um atributo cor=1
# 3) Adicionar um atributo fabricante=3
# 4) Criar um índice vazio
# 5) Imprimir o valor da chave ocupacao

empty_dict = {} # Cria um dicionário vazio
d1 = {'tipo' : 'carro', 'ano':2020, 'ocup' : [1, 2]} # Cria um dicionário
d1['cor'] = 1 # Cria um novo par chave-valor
d1['fabric'] = 3 # Cria um novo par chave-valor
print(d1)
print(d1['ocup'])

{'ocup': [1, 2], 'ano': 2020, 'fabric': 3, 'tipo': 'carro', 'cor': 1}
[1, 2]


### Outros métodos relacionados a dicionários

In [12]:
# 1) Crie o seguinte dicionário: d1 = {'tipo' : 'carro', 'ano':2020, 'ocup' : [1, 2]} 
# 2) Teste se 'tipo' está dentre as chaves de d1 
# 3) Remova o par identificado por 'ano'
# 4) Remova o par identificado por 'ocup' e retorne o seu valor
# 5) Imprima a lista de keys
# 6) Adicione esses pares {'motor' : '18c', 'dono' : 12} ao dicionário

d1 = {'tipo' : 'carro', 'ano':2020, 'ocup' : [1, 2]} 
print('tipo' in d1) # Testa: 'tipo' está em d1.keys()?
del d1['ano'] # Remove o par identificado por 'ano'
ret = d1.pop('ocup') # Remove do dict e retorna o valor
print(list(d1.keys()))
d1.update({'motor' : '18c', 'dono' : 12}) #atualiza
print(d1)

True
['tipo']
{'motor': '18c', 'dono': 12, 'tipo': 'carro'}


## NumPy Arrays
### Operações vetorizadas em ndarrays
#### Mais eficientes (preferíveis)

In [2]:
# 1) Importe a biblioteca numpy e lhe dê o apelido np 
# 2) Crie um array (data) bidimensional de 2 linhas e 3 colunas de números aleatórios
# 3) Multiplique todos os elementos do vetor por 10
# 4) Some os elementos do array data a ele mesmo

import numpy as np # Importa a biblioteca numpy e lhe dá o apelido de np 
data = np.random.randn(2, 3) # Gerar dados aleatórios. 2L x 3C
print(data)
print(data * 10)
print(data + data)

[[ 1.98840382 -0.17662144  1.0884208 ]
 [ 0.10412073 -0.16798921  0.08936444]]
[[19.88403821 -1.76621437 10.88420803]
 [ 1.04120734 -1.67989212  0.89364438]]
[[ 3.97680764 -0.35324287  2.17684161]
 [ 0.20824147 -0.33597842  0.17872888]]


### Instruções inline (list comprehension)

In [14]:
# 1) Escreva uma instrução if else na forma inline
# Dica - Sintaxe: valor_se_verdadeiro if condicao else valor_se_falso
# 2) Escreva uma instrução de loop (for) na forma inline calculando [1, 4, 9 ... 100]
# Dica - Sintaxe: [ OPERACAO_VAL for VAL in SEQUENCIA ]

a = 2
# Sintaxe: valor_se_verdadeiro if condicao else valor_se_falso
b = 0 if a > 10 else 1  #Sintaxe: vv if cond else vf
print(b)
# [ OPERACAO_VAL for VAL in SEQUENCIA ]
resultado1 = [x for x in range(10)] # list comprehension
resultado2 = [x * x for x in range(10)]
print(resultado1)
print(resultado2)

1
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


### Comparação de Desempenho: Numpy array vs list

In [18]:
# 1) Crie um numpy array com 10 milhoes de numeros sequenciais
# 2) Crie uma lista 10 milhoes de numeros sequenciais
# 3) Meça o tempo de multiplicar todos os elementos do array por 2
# 4) Meça o tempo de multiplicar todos os elementos da lista por 2
# Dica: %time mede o tempo tomado pela execução da linha
# Dica: Não precisa importar a biblioteca numpy novamente. 
#       Ela foi importada na célula 19, acima.

my_arr = np.arange(10000000) # Função que cria um array de números sequenciais
my_list = list(range(10000000))
# %time mede o tempo tomado pela execução da linha
%time my_arr2 = my_arr * 2
%time my_list2 = [x * 2 for x in my_list]
print(my_arr2[1:5])
print(my_list2[1:5])

Wall time: 23 ms
Wall time: 1.27 s
[2 4 6 8]
[2, 4, 6, 8]


### Criando ndarrays

In [5]:
# 1) Crie um array unidimensional a partir da lista [6, 7.5, 8, 0, 1]
# 2) Crie um array bidimensional a partir da lista [[1, 2, 3, 4], [5, 6, 7, 8]]
# 3) Crie um array unidimensional de zeros

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(np.zeros(5)) # Função que cria um array de zeros

[6.  7.5 8.  0.  1. ]
[[1 2 3 4]
 [5 6 7 8]]
[0. 0. 0. 0. 0.]


In [6]:
# 1) Crie o seguinte array arr1 = np.array([6, 7.5, 8, 0, 1])
# 2) Imprima o tipo do dado do array arr1
# 3) Crie o seguinte array arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.int32)
# 4) Imprima o shape e o número de dimensões do array arr2

# O tipo do dado é inferido. Mas também pode ser especificado
arr1 = np.array([6, 7.5, 8, 0, 1])
print(arr1.dtype) # tipo do dado
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.int32)
print(arr2.shape) # Forma/dimensões do array
print(arr2.ndim) # Quantidade de dimensões

float64
(2L, 4L)
2


### Conversão de tipos (cast)

In [12]:
# 1) Crie o seguinte array num_str = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
# 2) Converta-o para o tipo float
# 3) Crie o seguinte array arr1 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
# 4) Converta-o para o tipo int32

num_str = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
arr_float = num_str.astype(float) # Converte para float
print(arr_float)
arr1 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr1_int = arr1.astype(np.int32) # Converte para int32
print(arr1_int)

[ 1.25 -9.6  42.  ]
[ 3 -1 -2  0 12 10]


### Aritmética com NumPy Arrays

In [14]:
# 1) Crie os seguintes arrays arr = np.array([1., 2., 3.]) e arr2 = np.array([4., 5., 6.])
# 2) Calcule arr * arr
# 3) Calcule arr - arr
# 4) Calcule 1 / arr
# 5) Calcule a raiz quadrada dos elementos de arr
# 6) Calcule arr - arr
# 7) Compare os elementos do array arr com os elementos do arr2

arr = np.array([1., 2., 3.])
arr2 = np.array([4., 5., 6.])
print(arr * arr)
print(arr - arr)
print(1 / arr)
print(arr ** 0.5)
print(arr2 > arr)

[1. 4. 9.]
[0. 0. 0.]
[1.         0.5        0.33333333]
[1.         1.41421356 1.73205081]
[ True  True  True]


### Slicing (fatiar) NumPy Arrays
#### Nas listas os slices são cópias
#### Nos arrays numpy os slices são views (visualizações)

In [21]:
# 1) Crie o seguinte array: arr = np.arange(10)
# 2) Guarde na variavel arr_slice os elementos de índice 5 até 8 deste array
# 3) Atribua o valor 12345 ao elemento de índice 1 do array arr_slice
# 4) Visualize o arr e perceba que o elemento de índice 6 alterou de valor
# 5) Crie a seguinte lista: li2 = list(range(10))
# 6) Guarde na variavel list_slice os elementos de índice 5 até 8 da lista li2
# 7) Atribua o valor 12345 ao elemento de índice 1 da lista list_slice
# 8) Visualize a lista li2 e perceba que o elemento de índice 6 alterou de valor

arr = np.arange(10)
print(arr)
arr_slice = arr[5:8]
arr_slice[1] = 12345
print(arr)
li2 = list(range(10)) # Repetindo a operação equivalente com uma lista
list_slice = li2[5:8]
list_slice[1] = 12345
print(li2)

[0 1 2 3 4 5 6 7 8 9]
[    0     1     2     3     4     5 12345     7     8     9]


### Slicing (fatiar) de arrays bidimensionais

In [4]:
# 1) Crie o seguinte array: arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 2) Imprima o shape desse array
# 3) Imprima a linha de índice 2 desse array
# 4) Imprima o elemento de posição 0,2 desse array, usando as sintaxes com e sem vírgula

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d.shape)
print(arr2d[2])
print(arr2d[0][2]) # Tanto faz
print(arr2d[0, 2]) # Tanto faz

(3L, 3L)
[7 8 9]
3
3
